### ISSUE TITLE
Benchmark `loading-benchmark` fails to build with GHC 7.10

### ISSUE THREAD

**Issue by andreasabel** [acid-state/acid-state#139]
https://github.com/andreasabel/acid-state/runs/5173813620?check_suite_focus=true#step:19:98
```
Building benchmark 'loading-benchmark' for acid-state-0.16.0.1..
...
[4 of 4] Compiling Main             ( benchmarks/loading/Benchmark.hs, /__w/acid-state/acid-state/dist-newstyle/build/x86_64-linux/ghc-7.10.3/acid-state-0.16.0.1/b/loading-benchmark/build/loading-benchmark/loading-benchmark-tmp/Main.o )

benchmarks/loading/Benchmark.hs:89:34: Not in scope: ‘perRunEnv’
```

**Comment by ddssff** [comment]
Wait so this is resolved?

**Comment by andreasabel** [comment]
> Wait so this is resolved?

Depends.  For the latest versions of acid-state, yes (see list above).  I did not fix all of the acid-state build plans, because matrix.hackage is still broken and maybe no one cares about older versions of acid-state.

So, practically, yes.  
Theoretically, no, all versions out there that use `perRunEnv` without `criterion >= 1.2`are still broken.
But fine to close the issue and wait if someone comes complaining...
