### ISSUE TITLE
Failed to build acid-state-0.15.1

### ISSUE THREAD

**Issue by marco-comini** [acid-state/acid-state#127]
Hi folks,
  I hope this is not a duplicated Issue (I've not found something related).

I've just tried to install acid-state-0.15.1 in a fresh installation of ghc 8.6.5 and it fails with this error

> src/Data/Acid/Local.hs:234:10: error:
    • Could not deduce (Typeable s)
        arising from a use of ‘safecopy-0.10.0:Data.SafeCopy.SafeCopy.$dmerrorTypeName’
      from the context: SafeCopy s
        bound by the instance declaration
        at src/Data/Acid/Local.hs:234:10-46
    • In the expression:
        safecopy-0.10.0:Data.SafeCopy.SafeCopy.$dmerrorTypeName
          @(Checkpoint s)
      In an equation for ‘errorTypeName’:
          errorTypeName
            = safecopy-0.10.0:Data.SafeCopy.SafeCopy.$dmerrorTypeName
                @(Checkpoint s)
      In the instance declaration for ‘SafeCopy (Checkpoint s)’
    |
234 | instance SafeCopy s => SafeCopy (Checkpoint s) where

can someone tell me what I'm doing wrong?
Thanks.

**Comment by ddssff** [comment]
This is a consequence of the new release of safecopy.  We need to mark that version of acid state to require safecopy < 0.10.

**Comment by stepcut** [comment]
Do we also need to upload an `acid-state` that works with `safecopy 0.10`?

**Comment by ddssff** [comment]
It is on its way.

**Comment by ddssff** [comment]
I have submitted a pull request.

**Comment by marco-comini** [comment]
If it can be of any help, I've successfully built version 1.15.0 with safe copy-0.10

**Comment by ddssff** [comment]
I'm a little surprised by that - maybe you got the metadata changes I submitted a little while ago for acid-state-0.15.0  and it actually build with safecopy-0.9?  Anyway, acid-state-0.15.2 is on its way.

**Comment by stepcut** [comment]
`acid-state-0.15.1` is now marked as required `safecopy < 0.10`.  `acid-state-0.15.2` is now on hackage and works with `safecopy 0.10`.

**Comment by marco-comini** [comment]
> I'm a little surprised by that - maybe you got the metadata changes I submitted a little while ago for acid-state-0.15.0 and it actually build with safecopy-0.9? Anyway, acid-state-0.15.2 is on its way.

I don't think so. Right after having submitted the issue I thought to try building version 1.15.0 in case the "bug" was introduced by the new version. The version installed of safecopy was 1.10 and I had not run any 'cabal update' since then (isn't this the only way metadata can change?). However I did not pay attention if by chance an older version of safecopy  has been installed in the process.  

Btw, thanks a lot for having reacted immediately!
