### ISSUE TITLE
acid-state fails to build with GHC 8.8.1

### ISSUE THREAD

**Issue by vmchale** [acid-state/acid-state#129]
It seems to need a tighter bound on `template-haskell`, and maybe an update.

The error message is:

```
[10 of 16] Compiling Data.Acid.TemplateHaskell ( src/Data/Acid/TemplateHaskell.hs, /home/vanessa/git-builds/junk/acid-state-0.15.2/dist-newstyle/build/x86_64-linux/ghc-8.8.1/acid-state-0.15.2/build/Data/Acid/TemplateHaskell.o )

src/Data/Acid/TemplateHaskell.hs:377:11: error:
    • Couldn't match expected type ‘(TypeQ -> TySynEqnQ) -> DecQ’
                  with actual type ‘Q Dec’
    • The function ‘tySynInstD’ is applied to two arguments,
      but its type ‘TySynEqnQ -> Q Dec’ has only one
      In the expression:
        tySynInstD
          ''MethodResult (tySynEqn [structType] (return resultType))
      In the third argument of ‘instanceD’, namely
        ‘[tySynInstD
            ''MethodResult (tySynEqn [structType] (return resultType)),
          tySynInstD
            ''MethodState (tySynEqn [structType] (return stateType))]’
    |
377 |         [ tySynInstD ''MethodResult (tySynEqn [structType] (return resultType))
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Data/Acid/TemplateHaskell.hs:377:22: error:
    • Couldn't match type ‘Name’ with ‘Q TySynEqn’
      Expected type: TySynEqnQ
        Actual type: Name
    • In the first argument of ‘tySynInstD’, namely ‘''MethodResult’
      In the expression:
        tySynInstD
          ''MethodResult (tySynEqn [structType] (return resultType))
      In the third argument of ‘instanceD’, namely
        ‘[tySynInstD
            ''MethodResult (tySynEqn [structType] (return resultType)),
          tySynInstD
            ''MethodState (tySynEqn [structType] (return stateType))]’
    |
377 |         [ tySynInstD ''MethodResult (tySynEqn [structType] (return resultType))
    |                      ^^^^^^^^^^^^^^

src/Data/Acid/TemplateHaskell.hs:377:47: error:
    • Couldn't match expected type ‘Maybe [TyVarBndr]’
                  with actual type ‘[TypeQ]’
    • In the first argument of ‘tySynEqn’, namely ‘[structType]’
      In the second argument of ‘tySynInstD’, namely
        ‘(tySynEqn [structType] (return resultType))’
      In the expression:
        tySynInstD
          ''MethodResult (tySynEqn [structType] (return resultType))
    |
377 |         [ tySynInstD ''MethodResult (tySynEqn [structType] (return resultType))
    |                                               ^^^^^^^^^^^^

src/Data/Acid/TemplateHaskell.hs:378:11: error:
    • Couldn't match expected type ‘(TypeQ -> TySynEqnQ) -> DecQ’
                  with actual type ‘Q Dec’
    • The function ‘tySynInstD’ is applied to two arguments,
      but its type ‘TySynEqnQ -> Q Dec’ has only one
      In the expression:
        tySynInstD ''MethodState (tySynEqn [structType] (return stateType))
      In the third argument of ‘instanceD’, namely
        ‘[tySynInstD
            ''MethodResult (tySynEqn [structType] (return resultType)),
          tySynInstD
            ''MethodState (tySynEqn [structType] (return stateType))]’
    |
378 |         , tySynInstD ''MethodState  (tySynEqn [structType] (return stateType))
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Data/Acid/TemplateHaskell.hs:378:22: error:
    • Couldn't match type ‘Name’ with ‘Q TySynEqn’
      Expected type: TySynEqnQ
        Actual type: Name
    • In the first argument of ‘tySynInstD’, namely ‘''MethodState’
      In the expression:
        tySynInstD ''MethodState (tySynEqn [structType] (return stateType))
      In the third argument of ‘instanceD’, namely
        ‘[tySynInstD
            ''MethodResult (tySynEqn [structType] (return resultType)),
          tySynInstD
            ''MethodState (tySynEqn [structType] (return stateType))]’
    |
378 |         , tySynInstD ''MethodState  (tySynEqn [structType] (return stateType))
    |                      ^^^^^^^^^^^^^

src/Data/Acid/TemplateHaskell.hs:378:47: error:
    • Couldn't match expected type ‘Maybe [TyVarBndr]’
                  with actual type ‘[TypeQ]’
    • In the first argument of ‘tySynEqn’, namely ‘[structType]’
      In the second argument of ‘tySynInstD’, namely
        ‘(tySynEqn [structType] (return stateType))’
      In the expression:
        tySynInstD ''MethodState (tySynEqn [structType] (return stateType))
    |
378 |         , tySynInstD ''MethodState  (tySynEqn [structType] (return stateType))
    |                                               ^^^^^^^^^^^^
cabal: Failed to build acid-state-0.15.2 (which is required by
```

Cheers
