### PR TITLE
Fix build with unix-2.8, try GHC 9.6 on CI

### LINKED ISSUE #155: Build failure with unix-2.8 (GHC 9.6)
GHC 9.6 ships with `unix-2.8.0.0` which has an API change affecting us:
```
src-unix/FileIO.hs:19:32: error: [GHC-83865]
    • Couldn't match expected type: unix-2.8.0.0:System.Posix.IO.Common.OpenFileFlags
                                    -> IO Fd
                  with actual type: IO Fd
    • The function ‘openFd’ is applied to four value arguments,
        but its type ‘FilePath
                      -> OpenMode
                      -> unix-2.8.0.0:System.Posix.IO.Common.OpenFileFlags
                      -> IO Fd’
        has only three
      In the second argument of ‘($)’, namely
        ‘openFd filename WriteOnly (Just stdFileMode) defaultFileFlags’
      In the expression:
        fmap FHandle
          $ openFd filename WriteOnly (Just stdFileMode) defaultFileFlags
   |
19 | open filename = fmap FHandle $ openFd filename WriteOnly (Just stdFileMode) defaultFileFlags
   |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Failed to build acid-state-0.16.1.1
```

I revised the published versions of `acid-state` with bound `unix < 2.8`.

### PR DESCRIPTION
**Pull request by andreasabel**
Fixes #155:
- #155

### CODE REVIEW

**Comment by andreasabel** [comment]
A test fails on the [GHC 9.6.0 workflow](https://github.com/acid-state/acid-state/actions/runs/4122512413/jobs/7119794356#step:20:39):
```
ChangeState test
This example simulates what happens when you modify your state type
without telling AcidState how to migrate from the old version to the new.
Hopefully this program will fail with a readable error message.

examples: state/ChangeState/open.lock: openFdAt: does not exist (No such file or directory)
```
This should be investigated, might be connected to `unix-2.8.0.0`.

**Comment by andreasabel** [comment]
I chased the test failure upstream to:
- https://github.com/takano-akio/filelock/issues/12

File: src-unix/FileIO.hs [hunk 1]
```diff
@@ -16,7 +19,11 @@ data FHandle = FHandle Fd
 
 -- should handle opening flags correctly
 open :: FilePath -> IO FHandle
+#if !MIN_VERSION_unix(2,8,0)
 open filename = fmap FHandle $ openFd filename WriteOnly (Just stdFileMode) defaultFileFlags
+#else
+open filename = fmap FHandle $ openFd filename WriteOnly defaultFileFlags
```
Comment (andreasabel) [inline src-unix/FileIO.hs:25]: Likely wrong, see [takano-akio/filelock@`d93257d` (#13)](https://github.com/takano-akio/filelock/pull/13/commits/d93257d1721e4e711b64a0448f417e1fdb080c71).  Should be:
```haskell
open filename = fmap FHandle $ openFd filename WriteOnly defaultFileFlags{ creat = Just stdFileMode }
```
